// OverlayAddIn.idl : type library source for OverlayAddIn.dll
// This file will be processed by the MIDL compiler to produce the
// type library (OverlayAddIn.tlb).

import "ocidl.idl";
import "oaidl.idl";

[
	uuid(EC6A0FB7-A1C9-4DA9-9ECF-5BC74147D88E),
	version(1.0),
	helpstring("OverlayAddIn 1.0 Type Library")
]
library OverlayAddIn
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	importlib("framewrk.tlb");

	[ hidden, uuid(E156A752-3F5A-4086-B539-00E436537BFB) ]
	coclass MySolidEdgeAddIn
	{
		[default] interface IUnknown;
	};

	[ hidden, uuid(CB2E2DDC-1827-11D3-926A-00C04F79BE98) ]
	coclass TIMBOAddInEvents
	{
		[default] interface ISEAddInEvents;
	}

	[ hidden, uuid(CB2E2DD5-1827-11D3-926A-00C04F79BE98) ]
	coclass Commands
	{
		[default] interface IUnknown;
	}

	[ hidden, uuid(CB2E2DD6-1827-11D3-926A-00C04F79BE98) ]
	coclass TIMBOCommand
	{
		[default] interface IUnknown;
	}

	[ hidden, uuid(CB2E2DD7-1827-11D3-926A-00C04F79BE98) ]
	coclass TIMBOApplicationEvents
	{
		[default] interface IUnknown;
	}

	[ hidden, uuid(CB2E2DD9-1827-11D3-926A-00C04F79BE98) ]
	coclass CommandEvents
	{
		[default] interface ISECommandEvents;
	}

	[ hidden, uuid(CB2E2DDA-1827-11D3-926A-00C04F79BE98) ]
	coclass MouseEvents
	{
		[default] interface ISEMouseEvents;
	}

	[ hidden, uuid(CB2E2DDB-1827-11D3-926A-00C04F79BE98) ]
	coclass CommandWindowEvents
	{
		[default] interface ISECommandWindowEvents;
	}

	[ hidden, uuid(CB2E2DDE-1827-11D3-926A-00C04F79BE98) ]
	coclass TIMBOView
	{
		[default] interface IUnknown;
	}

	[ hidden, uuid(CB2E2DE0-1827-11D3-926A-00C04F79BE98) ]
	coclass TIMBOViewEvents
	{
		[default] interface ISEViewEvents;
	}

	[ hidden, uuid(CB2E2DDF-1827-11D3-926A-00C04F79BE98) ]
	coclass TIMBOhDCDisplayEvents
	{
		[default] interface ISEhDCDisplayEvents;
	}

	[ hidden, uuid(CB2E2DE5-1827-11D3-926A-00C04F79BE98) ]

	coclass TIMBOGLDisplayEvents
	{
		[default] interface ISEIGLDisplayEvents;
	}
};
