'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ApiDemos.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FolderClosed_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FolderClosed_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FolderOpen_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FolderOpen_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://solidedgeinterop.codeplex.com.
        '''</summary>
        Friend ReadOnly Property InteropForSolidEdgeUrl() As String
            Get
                Return ResourceManager.GetString("InteropForSolidEdgeUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Method_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Method_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No active 2D window..
        '''</summary>
        Friend ReadOnly Property NoActive2dWindow() As String
            Get
                Return ResourceManager.GetString("NoActive2dWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No active 3D window..
        '''</summary>
        Friend ReadOnly Property NoActive3dWindow() As String
            Get
                Return ResourceManager.GetString("NoActive3dWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No active assembly document..
        '''</summary>
        Friend ReadOnly Property NoActiveAssemblyDocument() As String
            Get
                Return ResourceManager.GetString("NoActiveAssemblyDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No active document..
        '''</summary>
        Friend ReadOnly Property NoActiveDocument() As String
            Get
                Return ResourceManager.GetString("NoActiveDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No active draft document..
        '''</summary>
        Friend ReadOnly Property NoActiveDraftDocument() As String
            Get
                Return ResourceManager.GetString("NoActiveDraftDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No active part document..
        '''</summary>
        Friend ReadOnly Property NoActivePartDocument() As String
            Get
                Return ResourceManager.GetString("NoActivePartDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No active sheetmetal document..
        '''</summary>
        Friend ReadOnly Property NoActiveSheetMetalDocument() As String
            Get
                Return ResourceManager.GetString("NoActiveSheetMetalDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No geometry defined..
        '''</summary>
        Friend ReadOnly Property NoGeometryDefined() As String
            Get
                Return ResourceManager.GetString("NoGeometryDefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No parts lists in draft document..
        '''</summary>
        Friend ReadOnly Property NoPartsListsInDraftDocument() As String
            Get
                Return ResourceManager.GetString("NoPartsListsInDraftDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profile not closed..
        '''</summary>
        Friend ReadOnly Property ProfileNotClosed() As String
            Get
                Return ResourceManager.GetString("ProfileNotClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://solidedgesamples.codeplex.com.
        '''</summary>
        Friend ReadOnly Property SamplesForSolidEdgeUrl() As String
            Get
                Return ResourceManager.GetString("SamplesForSolidEdgeUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://support.industrysoftware.automation.siemens.com/training/se/106/api/webframe.html.
        '''</summary>
        Friend ReadOnly Property SolidEdgeSdkUrl() As String
            Get
                Return ResourceManager.GetString("SolidEdgeSdkUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://solidedgespy.codeplex.com.
        '''</summary>
        Friend ReadOnly Property SpyForSolidEdgeUrl() As String
            Get
                Return ResourceManager.GetString("SpyForSolidEdgeUrl", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
