Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34011
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ApiSamples


    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Breakpoint_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Breakpoint_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property FolderClosed_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("FolderClosed_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property FolderOpen_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("FolderOpen_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to http://solidedgeinterop.codeplex.com.
		''' </summary>
		Friend Shared ReadOnly Property InteropForSolidEdgeUrl() As String
			Get
				Return ResourceManager.GetString("InteropForSolidEdgeUrl", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Method_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Method_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No active 2D window..
		''' </summary>
		Friend Shared ReadOnly Property NoActive2dWindow() As String
			Get
				Return ResourceManager.GetString("NoActive2dWindow", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No active 3D window..
		''' </summary>
		Friend Shared ReadOnly Property NoActive3dWindow() As String
			Get
				Return ResourceManager.GetString("NoActive3dWindow", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No active assembly document..
		''' </summary>
		Friend Shared ReadOnly Property NoActiveAssemblyDocument() As String
			Get
				Return ResourceManager.GetString("NoActiveAssemblyDocument", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No active document..
		''' </summary>
		Friend Shared ReadOnly Property NoActiveDocument() As String
			Get
				Return ResourceManager.GetString("NoActiveDocument", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No active draft document..
		''' </summary>
		Friend Shared ReadOnly Property NoActiveDraftDocument() As String
			Get
				Return ResourceManager.GetString("NoActiveDraftDocument", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No active part document..
		''' </summary>
		Friend Shared ReadOnly Property NoActivePartDocument() As String
			Get
				Return ResourceManager.GetString("NoActivePartDocument", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No active sheetmetal document..
		''' </summary>
		Friend Shared ReadOnly Property NoActiveSheetMetalDocument() As String
			Get
				Return ResourceManager.GetString("NoActiveSheetMetalDocument", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No geometry defined..
		''' </summary>
		Friend Shared ReadOnly Property NoGeometryDefined() As String
			Get
				Return ResourceManager.GetString("NoGeometryDefined", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No parts lists in draft document..
		''' </summary>
		Friend Shared ReadOnly Property NoPartsListsInDraftDocument() As String
			Get
				Return ResourceManager.GetString("NoPartsListsInDraftDocument", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Profile not closed..
		''' </summary>
		Friend Shared ReadOnly Property ProfileNotClosed() As String
			Get
				Return ResourceManager.GetString("ProfileNotClosed", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Run_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Run_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to http://solidedgesamples.codeplex.com.
		''' </summary>
		Friend Shared ReadOnly Property SamplesForSolidEdgeUrl() As String
			Get
				Return ResourceManager.GetString("SamplesForSolidEdgeUrl", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to http://support.industrysoftware.automation.siemens.com/training/se/106/api/webframe.html.
		''' </summary>
		Friend Shared ReadOnly Property SolidEdgeSdkUrl() As String
			Get
				Return ResourceManager.GetString("SolidEdgeSdkUrl", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to http://solidedgespy.codeplex.com.
		''' </summary>
		Friend Shared ReadOnly Property SpyForSolidEdgeUrl() As String
			Get
				Return ResourceManager.GetString("SpyForSolidEdgeUrl", resourceCulture)
			End Get
		End Property
	End Class
End Namespace
