//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSamples {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiSamples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Breakpoint_16x16 {
            get {
                object obj = ResourceManager.GetObject("Breakpoint_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderClosed_16x16 {
            get {
                object obj = ResourceManager.GetObject("FolderClosed_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderOpen_16x16 {
            get {
                object obj = ResourceManager.GetObject("FolderOpen_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://solidedgeinterop.codeplex.com.
        /// </summary>
        internal static string InteropForSolidEdgeUrl {
            get {
                return ResourceManager.GetString("InteropForSolidEdgeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Method_16x16 {
            get {
                object obj = ResourceManager.GetObject("Method_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active 2D window..
        /// </summary>
        internal static string NoActive2dWindow {
            get {
                return ResourceManager.GetString("NoActive2dWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active 3D window..
        /// </summary>
        internal static string NoActive3dWindow {
            get {
                return ResourceManager.GetString("NoActive3dWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active assembly document..
        /// </summary>
        internal static string NoActiveAssemblyDocument {
            get {
                return ResourceManager.GetString("NoActiveAssemblyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active document..
        /// </summary>
        internal static string NoActiveDocument {
            get {
                return ResourceManager.GetString("NoActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active draft document..
        /// </summary>
        internal static string NoActiveDraftDocument {
            get {
                return ResourceManager.GetString("NoActiveDraftDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active part document..
        /// </summary>
        internal static string NoActivePartDocument {
            get {
                return ResourceManager.GetString("NoActivePartDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active sheetmetal document..
        /// </summary>
        internal static string NoActiveSheetMetalDocument {
            get {
                return ResourceManager.GetString("NoActiveSheetMetalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No geometry defined..
        /// </summary>
        internal static string NoGeometryDefined {
            get {
                return ResourceManager.GetString("NoGeometryDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parts lists in draft document..
        /// </summary>
        internal static string NoPartsListsInDraftDocument {
            get {
                return ResourceManager.GetString("NoPartsListsInDraftDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not closed..
        /// </summary>
        internal static string ProfileNotClosed {
            get {
                return ResourceManager.GetString("ProfileNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Run_16x16 {
            get {
                object obj = ResourceManager.GetObject("Run_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://solidedgesamples.codeplex.com.
        /// </summary>
        internal static string SamplesForSolidEdgeUrl {
            get {
                return ResourceManager.GetString("SamplesForSolidEdgeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://support.industrysoftware.automation.siemens.com/training/se/106/api/webframe.html.
        /// </summary>
        internal static string SolidEdgeSdkUrl {
            get {
                return ResourceManager.GetString("SolidEdgeSdkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://solidedgespy.codeplex.com.
        /// </summary>
        internal static string SpyForSolidEdgeUrl {
            get {
                return ResourceManager.GetString("SpyForSolidEdgeUrl", resourceCulture);
            }
        }
    }
}
