// AddInDemo.idl : IDL source for AddInDemo
//

// This file will be processed by the MIDL tool to
// produce the type library (AddInDemo.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(9444609D-8C66-4659-89F5-14451BB5F65A),
	version(1.0)	
]
library AddInDemoLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	importlib("framewrk.tlb");

	[ uuid(EE3C24E4-BB07-4C3F-909C-031C84EC3F07) ]
	coclass MyAddIn
	{
		[default] interface IUnknown;
	};

	//[ hidden, uuid(35F69A4E-1681-4745-B192-0A55B2843D0F) ]
	//coclass ASMLOCAddInEventsEx
	//{
	//	[default] interface ISEAddInEventsEx;
	//}

	//[ hidden, uuid(6D4144F3-2FC2-11D3-9276-00C04F79BE98) ]
	//
	//coclass ASMLOCAddInEvents
	//{
	//	[default] interface ISEAddInEvents;
	//}

	//[ hidden, uuid(104A396A-DE35-46b6-8806-754A7A4CCCB8) ]
	//coclass ASMLOCApplicationEvents
	//{
	//	[default] interface IUnknown;
	//}

	//[ hidden, uuid(D3DEF212-1809-4aeb-8C93-9745AA28ACF8) ]
	//
	//coclass ASMLOCAddInEdgeBarEvents
	//{
	//	[default] interface ISEAddInEdgeBarEvents;
	//}

	//[ hidden, uuid(6D4144EC-2FC2-11D3-9276-00C04F79BE98) ]
	//
	//coclass Commands
	//{
	//	[default] interface IUnknown;
	//}

	//[ hidden, uuid(6D4144ED-2FC2-11D3-9276-00C04F79BE98) ]
	//
	//coclass ASMLOCCommand
	//{
	//	[default] interface IUnknown;
	//}

	//[ hidden, uuid(6D4144F0-2FC2-11D3-9276-00C04F79BE98) ]
	//
	//coclass CommandEvents
	//{
	//	[default] interface ISECommandEvents;
	//}

	//[ hidden, uuid(6D4144F1-2FC2-11D3-9276-00C04F79BE98) ]
	//
	//coclass MouseEvents
	//{
	//	[default] interface ISEMouseEvents;
	//}

	//[hidden, uuid(D0BE7F5A-F2C5-4a30-94C8-C96FED316DEF) ]
	//
	//coclass LocateFilterEvents
	//{
	//	[default] interface ISELocateFilterEvents;
	//}

	//[ hidden, uuid(6D4144F2-2FC2-11D3-9276-00C04F79BE98) ]
	//
	//coclass CommandWindowEvents
	//{
	//	[default] interface ISECommandWindowEvents;
	//}

	//[ hidden, uuid(6347FC9F-8E34-4f07-80C4-9FD9DF23CAA7) ]
	//
	//coclass ADDINDocument
	//{
	//	[default] interface IUnknown;
	//}

	//[ hidden, uuid(1E6DA6E8-090A-4580-A807-F8BF783786E8) ]
	//
	//coclass ADDINDocumentEvents
	//{
	//	[default] interface ISEDocumentEvents;
	//}
};
